<?php

/**
 * @file
 * Allows administrators to inject VAR into the page output based on
 * configurable rules. Useful for adding simple VAR tweaks without modifying
 * a site's official theme.
 */

/**
 * Implementation of hook_help().
 */
function hp_import_export_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/settings/modules#description':
      $output .= t('Allows Import and Export variables based on configurable rules.');
      break;
    case 'admin/hp_import_export':
      break;
  }
  return $output;
}

/**
 * Implementation of hook_init().
 * Checks to see whether any VAR files should be added to the current page,
 * based on rules configured by the site administrator.
 */
function hp_import_export_init() {
}

/**
 * Implementation of hook_menu().
 * Defines menu callbacks for VAR Injector's configuration pages.
 */
function hp_import_export_menu() {
  $items = array(
    'admin/hp_import_export' => array(
      ....
      'file' => 'hp_import_export.admin.inc',
    ),
    'admin/hp_import_export/import' => array(
      ....
      'file' => 'hp_import_export.admin.inc',
      'type' => MENU_CALLBACK,
    ),
    'admin/hp_import_export/export' => array(
      ....
      'file' => 'hp_import_export.admin.inc',
      'type' => MENU_CALLBACK,
    ),
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 */
function hp_import_export_theme() {
  $items['hp_import_export_admin_form'] = array(
    'arguments' => array('form' => array()),
    'file' => 'hp_import_export.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function hp_import_export_perm() {
  return array('administer variables');
}
